name: Scan Docker Image
description: Security scan of Docker Image

inputs:
    repository:
        required: true

    registry:
        required: true

    image-tag:
        required: true

runs:
    using: composite

    steps:

      ##################################################
      # Download Docker Artifact
      ##################################################
      - name: Download Docker Artifact
        uses: actions/download-artifact@v4
        with: 
            name: docker-image


      ##################################################
      # Load Docker Image
      ##################################################
      - name: Load Docker Image
        shell: bash
        run: |
            docker load -i image.tar


      ##################################################
      # Run Trivy Scan
      ##################################################
      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}
            format: table