name: Docker Build And Push
description: Build Docker Image, Tag it and Push to Amazon ( AWS ) ECR ( Elastic Container Registry )

inputs:
    repository:
        required: true

    registry:
        required: true

    image-tag:
        required: true

outputs:
    image-tag:
        description: Docker Image Tag
        value: ${{ inputs.image-tag }}


runs:
    using: composite

    steps:
    
    ##################################################
    # Build Docker Image
    ##################################################
      - name: Build Docker Image
        run: |
            docker build -t ${{ inputs.repository }}:${{ inputs.image-tag }} .
        shell: bash


    ##################################################
    # Tag Docker Image
    ##################################################
      - name: Tag Docker Image
        run: |
            docker tag ${{ inputs.repository }}:${{ inputs.image-tag }} ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}


    ##################################################
    # Push Docker Image
    ##################################################
      - name: Push Docker Image
        shell: bash
        run: |
            docker push ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}