name: Build Docker Image & Tag
description: Build Docker Image & Tag

inputs:
    repository:
        required: true

    registry:
        required: true

    image-tag:
        required: true

outputs:
    image-tag:
        description: Docker Image Tag
        value: ${{ inputs.image-tag }}


runs:
    using: composite

    steps:
    
    ##################################################
    # Build Docker Image
    ##################################################
      - name: Build Docker Image
        shell: bash
        run: |
            docker build -t ${{ inputs.repository }}:${{ inputs.image-tag }} .


    ##################################################
    # Tag Docker Image
    ##################################################
      - name: Tag Docker Image
        shell: bash
        run: |
            docker tag ${{ inputs.repository }}:${{ inputs.image-tag }} ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}

