name: Docker Build And Push
description: Build Docker Image, Tag it and Push to Amazon ( AWS ) ECR ( Elastic Container Registry )

inputs:
    repository:
        required: true

    registry:
        required: true

    image-tag:
        required: true

runs:
    using: composite

    steps:

      ##################################################
      # Download Docker Artifact
      ##################################################
      - name: Download Docker Artifact
        uses: actions/download-artifact@v4
        with:
            name: docker-image

    
      ##################################################
      # Load Docker Image
      ##################################################
      - name: Load Docker Image
        shell: bash
        run: |
            docker load -i image.tar

      - name: Tag Docker Image For ECR
        shell: bash
        run: |
            docker tag \
                ${{ inputs.repository }}:${{ inputs.image-tag }} \
                ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}


      ##################################################
      # Push Docker Image
      ##################################################
      - name: Push Docker Image
        shell: bash
        run: |
            docker push ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}