name: Setup Node.Js
description: Setup Node.js and Install Project Dependencies

inputs:
    node-version:
        required: true

runs:
    using: composite

    steps:

      - name: Setup Node js
        uses: actions/setup-node@v4
        with:
            node-version: ${{ inputs.node-version }}
            cache: npm                                      #   To avoid to setup Node.js every time in each run.
            cache-dependency-path: package-lock.json        #   Cache manage file.


      - name: Install Dependencies
        shell: bash
        run: |
            npm install