name: Multi Environment Deployment Workflow

on: 
    push:
        branches:
            - develop
            - staging
            # - production


jobs:
    # Job Name, Job Name can be anything but unique within the same file.
    deploy-develop:

        # Condition to execute this job-setup only when push happen on develop branch
        if: github.ref_name == 'develop'

        # OS Like [ubuntu-latest, windows-latest, macOS-latest]
        # runs-on: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ubuntu-latest

        # Need to associate this job with develop environment
        environment: develop

        steps:
          - name: Print Branch Name
            run: |
                echo "Current Branch: ${{ github.ref_name }}"

          - name: Deploying to Develop
            run: |
                echo "Deploying application to Develop environment"

    deploy-staging:
        if: github.ref_name == 'staging'

        runs-on: ubuntu-latest

        environment: staging

        steps:
          - name: Print Branch Name
            run: |
                echo "Current Branch: ${{ github.ref_name }}"

          - name: Deploying To Staging
            run: |
                echo "Deploying application to Staging Branch"



