name: Multi Environment Deployment Workflow

on: 
    push:
        branches:
            - develop
            # - staging
            # - production

    pull_request:
        branches:
            - staging


jobs:
    # Job Name, Job Name can be anything but unique within the same file.
    deploy-develop:

        # Condition to execute this job-setup only when push happen on develop branch
        if: github.ref_name == 'develop'

        # OS Like [ubuntu-latest, windows-latest, macOS-latest]
        # runs-on: [ubuntu-latest, windows-latest, macOS-latest]
        runs-on: ubuntu-latest

        # Need to associate this job with develop environment
        environment: develop

        steps:
            # GITHUB ACTIONS CHECKOUT TO THE SOURCE BRANCH `DEVELOP` TO GET THE LATEST CODE
          - name: Checkout Source
            uses: actions/checkout@v4

            # CONFIGURE LOGIN CREDS FOR AWS CONSOLE TO PROCEED THE FURTHER THINGS
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

          - name: Login to ECR
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build Docker Image
            run: |
                docker build -t my-tech-profile-dev:${{ github.sha }} .

          - name: Tag Docker Image
            run: |
                docker tag my-tech-profile-dev:${{ github.sha }} \
                    128833122451.dkr.ecr.us-east-1.amazonaws.com/my-tech-profile-develop:${{ github.sha }}

          - name: Push Docker Image to AWS ECR
            run: |
                docker push 128833122451.dkr.ecr.us-east-1.amazonaws.com/my-tech-profile-develop:${{ github.sha }}


            # This step will fetch the current task definition in json format to update the task definition based on the latest docker image.
          - name: Fetch Current Task Definition
            run: |
                aws ecs describe-task-definition \
                    --task-definition Tech-Profile-TD-dev --query taskDefinition > task-definition.json


            # These two steps is most important, if you want to use the latest pushed image to use on your application.
            # 'Render ECS Task Definition' step will use to render the task definition and update it with the latest docker image.
          - name: Render ECS Task Definition
            id: task-def
            uses: aws-actions/amazon-ecs-render-task-definition@v1
            with:
                task-definition: task-definition.json
                container-name: my-tech-profile
                image: 128833122451.dkr.ecr.us-east-1.amazonaws.com/my-tech-profile-develop:${{ github.sha }}

            # This 'Deploy ECS Task Definition' use to pull the latest docker image from ECR and run it inside the container. 
          - name: Deploy ECS Task Definition
            uses: aws-actions/amazon-ecs-deploy-task-definition@v2
            with: 
                task-definition: ${{ steps.task-def.outputs.task-definition }}
                service: Tech-Profile-ECS-Service-dev
                cluster: Tech-Profile-ECS-Dev
                wait-for-service-stability: true




    deploy-staging:
        # if: github.ref_name == 'staging'      # ref_name represents the current branch name. From which the workflow is triggered.
        if: github.base_ref == 'staging'        # base_ref used in pull_request event. It represents the target branch where you want to merge your changes through PR.
        # In this case, changes push to develop branch and raise PR and then merge to staging branch.

        runs-on: ubuntu-latest

        environment: staging

        steps:
          - name: Checkout to Source
            uses: actions/checkout@v4

            # CONFIGURE LOGIN CREDS FOR AWS CONSOLE TO PROCEED THE FURTHER THINGS
          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials
            with: 
                aws-access-key-id: ${{ STAGE_AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ STAGE_AWS_SECRET_ACCESS_KEY }}

          - name: Login to ECR
            uses: aws-actions/amazon-ecr-login

          - name: Build Docker Image
            run: |
                docker build -t my-tech-profile-stage:${{github.sha}} .

          - name: Tag Docker Image
            run: |
                docker tag my-tech-profile-stage:${{github.sha}} \
                        128833122451.dkr.ecr.us-east-1.amazonaws.com/my-tech-profile-staging:${{github.sha}}

          - name: Push Docker Image to AWS ECR
            run: |
                docker push 128833122451.dkr.ecr.us-east-1.amazonaws.com/my-tech-profile-staging:${{github.sha}}




